### ISSUE TITLE
Switch from cookies to local storage for game state and high score

### ISSUE THREAD

**Issue by MikeBellika** [MikeBellika/tile-game#4]
I've seen cookies get overwritten and the code feels a bit ugly. The last time this happened was yesterday, when I tried to switch to static rendering. I want to migrate to cloudflare and I would feel more comfortable with this if state was stored in local storage.

There will need to be a transition period where the state is stored in both local storage and cookies, so that the state will not be lost.

**Comment by DeanWard** [comment]
Is the state small enough to encode into a url as a means to "transfer" it to another device? I'd love to be able to start a game on one device and then send myself a link and continue on another device.

**Comment by MikeBellika** [comment]
> Is the state small enough to encode into a url as a means to "transfer" it to another device? I'd love to be able to start a game on one device and then send myself a link and continue on another device.

That’s an excellent idea! I also want to implement sharing of high scores, so I’ll probably encode the state in the url for another purpose as well. 

The state can fit in 65 numbers (1 for each tile and the current score)

**Comment by MikeBellika** [comment]
Done in https://github.com/MikeBellika/tile-game/pull/12
